const { DatabaseSync } = require("node:sqlite");

const db = new DatabaseSync("packages/database/dev.db");
db.exec(`
PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS User (id TEXT PRIMARY KEY,email TEXT NOT NULL UNIQUE,firstName TEXT,lastName TEXT,passwordHash TEXT NOT NULL,emailVerifiedAt TEXT,refreshTokenHash TEXT,createdAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updatedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS Organization (id TEXT PRIMARY KEY,name TEXT NOT NULL,createdAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updatedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS OrganizationUser (id TEXT PRIMARY KEY,organizationId TEXT NOT NULL,userId TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'MEMBER',createdAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY (organizationId) REFERENCES Organization(id) ON DELETE CASCADE,FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE);
CREATE UNIQUE INDEX IF NOT EXISTS OrganizationUser_organizationId_userId_key ON OrganizationUser(organizationId,userId);
CREATE TABLE IF NOT EXISTS Document (id TEXT PRIMARY KEY,organizationId TEXT NOT NULL,ownerUserId TEXT NOT NULL,title TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'draft',createdAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updatedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY (organizationId) REFERENCES Organization(id) ON DELETE CASCADE,FOREIGN KEY (ownerUserId) REFERENCES User(id) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS Document_organizationId_createdAt_idx ON Document(organizationId,createdAt);
CREATE TABLE IF NOT EXISTS DocumentVersion (id TEXT PRIMARY KEY,documentId TEXT NOT NULL,storageKey TEXT NOT NULL,sha256 TEXT NOT NULL,pageCount INTEGER,createdAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY (documentId) REFERENCES Document(id) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS DocumentVersion_documentId_createdAt_idx ON DocumentVersion(documentId,createdAt);
CREATE TABLE IF NOT EXISTS Envelope (id TEXT PRIMARY KEY,organizationId TEXT NOT NULL,documentId TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'DRAFT',subject TEXT,message TEXT,signingOrder INTEGER NOT NULL DEFAULT 0,expiresAt TEXT,completedAt TEXT,createdAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updatedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY (organizationId) REFERENCES Organization(id) ON DELETE CASCADE,FOREIGN KEY (documentId) REFERENCES Document(id) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS Envelope_organizationId_status_createdAt_idx ON Envelope(organizationId,status,createdAt);
CREATE TABLE IF NOT EXISTS Recipient (id TEXT PRIMARY KEY,envelopeId TEXT NOT NULL,email TEXT NOT NULL,fullName TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'SIGNER',routingOrder INTEGER NOT NULL DEFAULT 1,status TEXT NOT NULL DEFAULT 'PENDING',accessToken TEXT,lastViewedAt TEXT,signedAt TEXT,createdAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY (envelopeId) REFERENCES Envelope(id) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS Recipient_envelopeId_routingOrder_idx ON Recipient(envelopeId,routingOrder);
CREATE TABLE IF NOT EXISTS Field (id TEXT PRIMARY KEY,envelopeId TEXT NOT NULL,recipientId TEXT,type TEXT NOT NULL,label TEXT,required INTEGER NOT NULL DEFAULT 1,page INTEGER NOT NULL,x REAL NOT NULL,y REAL NOT NULL,width REAL NOT NULL,height REAL NOT NULL,value TEXT,createdAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY (envelopeId) REFERENCES Envelope(id) ON DELETE CASCADE,FOREIGN KEY (recipientId) REFERENCES Recipient(id) ON DELETE SET NULL);
CREATE INDEX IF NOT EXISTS Field_envelopeId_page_idx ON Field(envelopeId,page);
CREATE TABLE IF NOT EXISTS Signature (id TEXT PRIMARY KEY,envelopeId TEXT NOT NULL,recipientId TEXT NOT NULL,fieldId TEXT NOT NULL,signatureType TEXT NOT NULL,storageKey TEXT NOT NULL,signedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,ipAddress TEXT,userAgent TEXT,FOREIGN KEY (envelopeId) REFERENCES Envelope(id) ON DELETE CASCADE,FOREIGN KEY (recipientId) REFERENCES Recipient(id) ON DELETE CASCADE,FOREIGN KEY (fieldId) REFERENCES Field(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS AuditLog (id TEXT PRIMARY KEY,envelopeId TEXT,actorUserId TEXT,action TEXT NOT NULL,details TEXT,ipAddress TEXT,userAgent TEXT,eventHash TEXT NOT NULL,prevEventHash TEXT,createdAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY (envelopeId) REFERENCES Envelope(id) ON DELETE SET NULL,FOREIGN KEY (actorUserId) REFERENCES User(id) ON DELETE SET NULL);
CREATE INDEX IF NOT EXISTS AuditLog_envelopeId_createdAt_idx ON AuditLog(envelopeId,createdAt);
CREATE TABLE IF NOT EXISTS Template (id TEXT PRIMARY KEY,organizationId TEXT NOT NULL,sourceDocumentId TEXT NOT NULL,name TEXT NOT NULL,schemaJson TEXT NOT NULL,createdAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updatedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY (organizationId) REFERENCES Organization(id) ON DELETE CASCADE,FOREIGN KEY (sourceDocumentId) REFERENCES Document(id) ON DELETE CASCADE);
`);

db.close();
console.log("SQLite schema ready.");

